name: basiqvoyager
recipe: lamp
config:
  php: '8.1'
  webroot: ./public 
  database: mariadb
services:
  appserver:
    xdebug: true
    overrides:
      environment:
        XDEBUG_MODE: "develop,debug"
